export const ErrorCodes = {
  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  INVALID_OTP: 'INVALID_OTP',
  EXPIRED_OTP: 'EXPIRED_OTP',
  INVALID_RESET_TOKEN: 'INVALID_RESET_TOKEN',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',

  // Resource
  NOT_FOUND: 'NOT_FOUND',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // Business Logic
  LOAD_EXCEEDS_AVAILABLE: 'LOAD_EXCEEDS_AVAILABLE',
  DELIVERY_ALREADY_PAID: 'DELIVERY_ALREADY_PAID',
  HANDOVER_ALREADY_SUBMITTED: 'HANDOVER_ALREADY_SUBMITTED',
  NO_ACTIVE_ASSIGNMENT: 'NO_ACTIVE_ASSIGNMENT',
  VAN_ALREADY_ASSIGNED: 'VAN_ALREADY_ASSIGNED',

  // Server
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
