export enum NotificationType {
  // Driver-facing
  VEHICLE_ASSIGNMENT = 'VEHICLE_ASSIGNMENT',
  HANDOVER_APPROVAL = 'HANDOVER_APPROVAL',
  PAYMENT_CONFIRMATION = 'PAYMENT_CONFIRMATION',

  // Admin-facing (driver activity)
  HANDOVER_SUBMITTED = 'HANDOVER_SUBMITTED',
  PAYMENT_SUBMITTED = 'PAYMENT_SUBMITTED',
  DELIVERY_RECORDED = 'DELIVERY_RECORDED',
  DAMAGED_EGGS_REPORTED = 'DAMAGED_EGGS_REPORTED',
}
